version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: rusard_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: rusard_backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - minio

  db:
    image: postgres:15
    container_name: rusard_db
    restart: always
    environment:
      POSTGRES_USER: rusard
      POSTGRES_PASSWORD: rusard
      POSTGRES_DB: rusard_site
    volumes:
      - ./data/db:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: rusard_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data

  nginx:
    image: nginx:alpine
    container_name: rusard_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
